Apparatus source tooltip popup
unfoldingWord-box3/greek-apparatus-app pull request #46
Opened 2020-12-13 06:47 UTC by ancientTexts-net

2020-12-13 10:29 UTC, richmahn requested changes

2020-12-13 10:29 UTC, richmahn commented on src/components/ApparatusData.js
> +                                <span className="tooltip mr-1">
Needs a key. Change to:

`                                <span key={`${i}-source-${j}-title`} className="tooltip mr-1">`

2020-12-13 14:29 UTC, richmahn commented on src/components/ApparatusData.js
> +                                <span className="tooltip mr-1">
Also, add `, j` to the map params on line 38

2020-12-14 13:07 UTC, ancientTexts-net reviewed
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-box3/greek-apparatus-app/46)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @richmahn)

___
*[src/components/ApparatusData.js, line 39 at r1](https://reviewable.io/reviews/unfoldingword-box3/greek-apparatus-app/46#-MOPqiafXly3n50byZfm-r1-39:-MOWMEwKC2lpKzOc66sI:b-896fix) ([raw file](https://github.com/unfoldingword-box3/greek-apparatus-app/blob/09f04ebf45409281fd1a44e5e3b280311e131635/src/components/ApparatusData.js#L39)):*
<details><summary><i>Previously, richmahn (Richard Mahn) wrote…</i></summary><blockquote>

Also, add `, j` to the map params on line 38
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-14 13:22 UTC, richmahn approved these changes
LGTM

2020-12-14 13:24 UTC, richmahn approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-box3/greek-apparatus-app/46#-:-MOWQ4gv3e9IKPR7WkQM:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ancientTexts-net)



<!-- Sent from Reviewable.io -->

2020-12-14 13:24 UTC, merged